import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar";
import { CheckIcon, Square3Stack3DIcon } from '@heroicons/react/20/solid'
import { useState } from 'react'
import { Dialog } from '@headlessui/react'
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'
import {Auth, Amplify, Storage } from 'aws-amplify';
import awsconfig from '../src/aws-exports.js';
import { Hub } from 'aws-amplify';
import { useEffect } from 'react';
import { ThemeProvider } from '@aws-amplify/ui-react';
import { Authenticator } from '@aws-amplify/ui-react';


const navigation = [
    { name: 'Home', href: '/' },
    { name: 'Models & Pricing', href: '/pricing' },
    { name: 'Docs', href: 'https://docs.usemeru.com' },
    { name: 'Blog', href: '/blog'}
  ]
  const components = {
    SignIn: {
      Header() {
        return (
          <>
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign in to your Account</h2>
          <p className="mt-2 text-center text-sm text-gray-600">Access Your API Key and Track Your Usage</p>
          </>
        );
      },
      
  
  },
  SignUp: {
    Header() {
      return (
        <>
        <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">Sign Up for Meru</h2>
        <p className="mt-2 text-center text-sm text-gray-600">Access Your API Key and Track Your Usage</p>
        </>
      );
    }}
  }
  export default  function MyMeru(){
        
        const [file, setFile] = useState(null);
        const [uploadingStatus, setUploadingStatus] = useState(false);
        async function handleChange(event) {
            Amplify.configure(awsconfig);
            if (event.target.files && event.target.files[0]) {
                const file = event.target.files[0];
                setFile(file)
                console.log(Storage)
                try {
                  await Storage.put('file.txt', 'file', {
                    bucket: 'meruv22b6021561fbd4beb977103fd2f77ba86111632-dev'
                  });
                } catch (error) {
                  console.log("Error uploading file: ", error);
                }
          };}
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
    const [hello, setHello] = useState(false);
    Hub.listen('auth', (data) => {
      switch (data.payload.event) {
        case 'signIn':
            console.log('user signed in');
            setHello(true)
        // case 'signUp':
        //     console.log('user signed up');
        //     break;
        // case 'signOut':
        //     console.log('user signed out');
        //     break;
        // case 'signIn_failure':
        //     console.log('user sign in failed');
        //     break;
        // case 'configured':
        //     console.log('the Auth module is configured');
      }
    });
    useEffect(() => {
      Auth.currentUserInfo().then((response) => setHello(response));
    }, []);
    if (hello){
        return (
          <>
          <div className={styles.container}>
            <Head>
              <title>Meru</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className="px-6 pt-6 lg:px-8">
              <div>
                <nav className="flex h-9 items-center justify-between" aria-label="Global">
                  <div className="flex lg:min-w-0 lg:flex-1" aria-label="Global">
                    <a href="#" className="-m-1.5 p-1.5">
                      <span className="sr-only">Meru</span>
                      <img className="h-10" src="logoreal.png" alt="logo" />
                    </a>
                  </div>
                  <div className="flex lg:hidden">
                    <button
                      type="button"
                      className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                      onClick={() => setMobileMenuOpen(true)}
                    >
                      <span className="sr-only">Open main menu</span>
                      <Bars3Icon className="h-6 w-6" aria-hidden="true" />
                    </button>
                  </div>
                  <div className="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
                    {navigation.map((item) => (
                      <a key={item.name} href={item.href} className="font-semibold text-gray-900 hover:text-gray-900">
                        {item.name}
                      </a>
                    ))}
                  </div>
                  <div className="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">
                    <a
                      href="/develop"
                      className="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-gray-900 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20"
                    >
                      My Dashboard
                    </a>
                  </div>
                </nav>
                <Dialog as="div" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
                  <Dialog.Panel focus="true" className="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
                    <div className="flex h-9 items-center justify-between">
                      <div className="flex">
                        <a href="#" className="-m-1.5 p-1.5">
                          <span className="sr-only">Meru</span>
                          <img
                            className="h-10"
                            src="logoreal.png"
                            alt=""
                          />
                        </a>
                      </div>
                      <div className="flex">
                        <button
                          type="button"
                          className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                          onClick={() => setMobileMenuOpen(false)}
                        >
                          <span className="sr-only">Close menu</span>
                          <XMarkIcon className="h-6 w-6" aria-hidden="true" />
                        </button>
                      </div>
                    </div>
                    <div className="mt-6 flow-root">
                      <div className="-my-6 divide-y divide-gray-500/10">
                        <div className="space-y-2 py-6">
                          {navigation.map((item) => (
                            <a
                              key={item.name}
                              href={item.href}
                              className="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10"
                            >
                              {item.name}
                            </a>
                          ))}
                        </div>
                        <div className="py-6">
                          <a
                            href="#"
                            className="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-gray-900 hover:bg-gray-400/10"
                          >
                            Log in
                          </a>
                        </div>
                      </div>
                    </div>
                  </Dialog.Panel>
                </Dialog>
              </div>
    
              <div className="bg-white">
          <div className="mx-auto max-w-7xl py-24 px-6 lg:px-8">
          <div className="relative isolate overflow-hidden bg-gradient-to-b from-indigo-100/20">
            <div className="mx-auto max-w-7xl pt-10 pb-24 sm:pb-32 lg:grid lg:grid-cols-2 lg:gap-x-8 lg:py-40 lg:px-8">
              <div className="px-6 lg:px-0 lg:pt-4">
                <div className="mx-auto max-w-2xl">
                  <div className="max-w-lg">
                    <h1 className="mt-0 text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
                      Chat with Your Content
                    </h1>
                    <p className="mt-6 text-lg leading-8 text-gray-600">
                      Gain insights faster by having a conversation with your content. Just upload a PDF, start asking questions, and get natural language responses. 
                    </p>
                    <div className="mt-10 flex items-center gap-x-6">
                      <a href="/densedataretrieval" className="text-base font-semibold leading-7 text-gray-900">
                       Add to your application with our API <span aria-hidden="true">→</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
    
              
              
                  <div class="flex justify-center">
      
                  <div class="flex justify-center mt-8">
        <div class="max-w-2xl rounded-lg shadow-xl bg-gray-50">
            <div class="m-4">
                <label class="inline-block mb-2 text-gray-500">Upload a PDF Document </label>
                <div class="flex items-center justify-center w-full">
                    <label
                        class="flex flex-col w-full h-32 border-4 border-blue-200 border-dashed hover:bg-gray-100 hover:border-gray-300">
                        <div class="flex flex-col items-center justify-center pt-7">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-8 h-8 text-gray-400 group-hover:text-gray-600"
                                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                            </svg>
                            <p class="pt-1 text-sm tracking-wider text-gray-400 group-hover:text-gray-600">
                                Attach a file</p>
                        </div>
                        <input onChange={handleChange} accept="" type="file" class="opacity-0" />
                    </label>
                </div>
            </div>
            <div class="flex justify-center p-2">
                <button class="w-full px-4 py-2 text-white bg-pink-600 rounded shadow-xl">Begin</button>
            </div>
        </div>
    </div> 
    </div>
    
              </div>
            </div>
    
        </div>
    
    
        <footer className="bg-white">
          <div className="mx-auto max-w-7xl overflow-hidden py-20 px-6 sm:py-24 lg:px-8">
            <nav className="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
              {navigation.map((item) => (
                <div key={item.name} className="pb-6">
                  <a href={item.href} className="text-sm leading-6 text-gray-600 hover:text-gray-900">
                    {item.name}
                  </a>
                </div>
              ))}
            </nav>
            <div className="mt-10 flex justify-center space-x-10">
              
            </div>
            <p className="mt-10 text-center text-xs leading-5 text-gray-500">
              &copy; 2023 Meru Productions, Inc. All rights reserved.
            </p>
          </div>
        </footer>
        </div>
        </div>
        </div>
        </>
    
        )
    }
    else{
      return(
        <>
        <Head>
          <title>Meru</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <div className="px-6 pt-6 lg:px-8">
          <div>
            <nav className="flex h-9 items-center justify-between" aria-label="Global">
              <div className="flex lg:min-w-0 lg:flex-1" aria-label="Global">
                <a href="#" className="-m-1.5 p-1.5">
                  <span className="sr-only">Meru</span>
                  <img className="h-10" src="logoreal.png" alt="logo" />
                </a>
              </div>
              <div className="flex lg:hidden">
                <button
                  type="button"
                  className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                  onClick={() => setMobileMenuOpen(true)}
                >
                  <span className="sr-only">Open main menu</span>
                  <Bars3Icon className="h-6 w-6" aria-hidden="true" />
                </button>
              </div>
              <div className="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-center lg:gap-x-12">
                {navigation.map((item) => (
                  <a key={item.name} href={item.href} className="font-semibold text-gray-900 hover:text-gray-900">
                    {item.name}
                  </a>
                ))}
              </div>
              <div className="hidden lg:flex lg:min-w-0 lg:flex-1 lg:justify-end">
                <a
                  href="/develop"
                  className="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-gray-900 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20"
                >
                  My Dashboard
                </a>
              </div>
            </nav>
            <Dialog as="div" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
              <Dialog.Panel focus="true" className="fixed inset-0 z-10 overflow-y-auto bg-white px-6 py-6 lg:hidden">
                <div className="flex h-9 items-center justify-between">
                  <div className="flex">
                    <a href="#" className="-m-1.5 p-1.5">
                      <span className="sr-only">Meru</span>
                      <img
                        className="h-10"
                        src="logoreal.png"
                        alt=""
                      />
                    </a>
                  </div>
                  <div className="flex">
                    <button
                      type="button"
                      className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      <span className="sr-only">Close menu</span>
                      <XMarkIcon className="h-6 w-6" aria-hidden="true" />
                    </button>
                  </div>
                </div>
                <div className="mt-6 flow-root">
                  <div className="-my-6 divide-y divide-gray-500/10">
                    <div className="space-y-2 py-6">
                      {navigation.map((item) => (
                        <a
                          key={item.name}
                          href={item.href}
                          className="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-400/10"
                        >
                          {item.name}
                        </a>
                      ))}
                    </div>
                    <div className="py-6">
                      <a
                        href="#"
                        className="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-gray-900 hover:bg-gray-400/10"
                      >
                        Log in
                      </a>
                    </div>
                  </div>
                </div>
              </Dialog.Panel>
            </Dialog>
          </div>
          <div className="flex min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
          <div className="w-full max-w-md space-y-8">
          <ThemeProvider
        theme={{
          tokens: {
            colors: {
              brand: {
                primary: {
                  10: '{colors.pink.10}',
                  20: '#F471B7',
                  40: '#F471B7',
                  60: '#F471B7',
                  80: '#F471B7',
                  90: '{colors.pink.60}',
                  100: '{colors.pink.60}',
                },
              },
            },
          },
        }}
      >
        <Authenticator.Provider>
  <Authenticator components={components} >
  <div className="flex mx-auto min-h-full items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div className="w-full max-w-md space-y-8">
  </div>
  </div>
  </Authenticator>
  </Authenticator.Provider>
  </ThemeProvider>
  </div>
  </div>
  </div>
        <footer className="bg-white">
        <div className="mx-auto max-w-7xl overflow-hidden py-20 px-6 sm:py-24 lg:px-8">
          <nav className="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
            {navigation.map((item) => (
              <div key={item.name} className="pb-6">
                <a href={item.href} className="text-sm leading-6 text-gray-600 hover:text-gray-900">
                  {item.name}
                </a>
              </div>
            ))}
          </nav>
          <div className="mt-10 flex justify-center space-x-10">
            
          </div>
          <p className="mt-10 text-center text-xs leading-5 text-gray-500">
            &copy; 2023 Meru Productions, Inc. All rights reserved.
          </p>
        </div>
      </footer>
      </>
      )
    }
}